site_name: Study Space DevSysOps
site_url: https://studyspace.nin.id.vn
site_description: Nơi lưu trữ học tập về Develop, System, Operations  của Nin
site_author: NinTech
# repo_url: https://github.com/nintech-sudo/studydevsysops


extra_css:
  - stylesheets/extra.css

theme:
  name: material
  locale: en
  language: en
  icon:
    repo: fontawesome/brands/github
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  font:
    text: Roboto
    code: Roboto Mono
  highlightjs: true
  palette:
    
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.sections
    - navigation.footer
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow 
    - navigation.top

  hljs_languages:
    - yaml
    - django
    - python
    - ruby
    - bash
    - shell
    - html

plugins:
  - search
  - open-in-new-tab
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
    #  - optimize:
    #  cache: true

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
     custom_checkbox: true

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true
      title: On this page
      toc_depth: 3
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra:
  analytics:
    provider: google
    property: G-RYW9ZPVJLX


validation:
  absolute_links: ignore
  unrecognized_links: ignore